<?php

namespace App\Http\Controllers;

use App\Models\Challan;
use App\Models\Dispatch;
use Barryvdh\DomPDF\Facade\Pdf;
use Illuminate\Support\Collection;
use ZipStream\ZipStream;

/**
 * Serves the Dealer (Master) and Farmer challans generated by
 * ChallanService::generateForDispatch() — one Master Dealer Challan per
 * dealer with 2+ farmers on a dispatch, plus one Farmer Challan each. Every
 * action here is authorized against the parent Dispatch (same rule as the
 * existing single-challan print/pdf in DispatchController), since a Challan
 * has no independent visibility rule of its own.
 *
 * Not to be confused with ChallanController, which is the unrelated,
 * pre-existing read-only listing/export of Dispatch.challan_no records.
 */
class ChallanDocumentController extends Controller
{
    public function show(Challan $challan)
    {
        $this->authorize('view', $challan->dispatch);

        return $this->renderSingle($challan);
    }

    public function pdf(Challan $challan)
    {
        $this->authorize('view', $challan->dispatch);

        [$view, $data] = $this->singleViewData($challan);

        return Pdf::loadView($view, $data)->download("{$challan->challan_no}.pdf");
    }

    /**
     * The QR code printed on every Dealer/Farmer challan encodes a signed
     * link to this route — same no-auth-guard, signed-middleware pattern as
     * PublicChallanController.
     */
    public function publicShow(Challan $challan)
    {
        return $this->renderSingle($challan, isPublic: true);
    }

    public function farmersPrint(Dispatch $dispatch)
    {
        $this->authorize('view', $dispatch);

        return view('challans.farmers-all', [
            'dispatch' => $dispatch,
            'farmerChallans' => $this->farmerEntries($dispatch),
        ]);
    }

    public function farmersPdf(Dispatch $dispatch)
    {
        $this->authorize('view', $dispatch);

        $pdf = Pdf::loadView('challans.farmers-all', [
            'dispatch' => $dispatch,
            'farmerChallans' => $this->farmerEntries($dispatch),
        ]);

        return $pdf->download("{$dispatch->dispatch_no}-farmer-challans.pdf");
    }

    public function printAll(Dispatch $dispatch)
    {
        $this->authorize('view', $dispatch);

        return view('challans.print-all', [
            'dispatch' => $dispatch,
            'sections' => $this->allSections($dispatch),
        ]);
    }

    /**
     * One PDF file per challan (Dealer + every Farmer), zipped together —
     * distinct from "Download All Farmer PDFs" above, which combines every
     * farmer into a single PDF rather than separate files.
     */
    public function zip(Dispatch $dispatch)
    {
        $this->authorize('view', $dispatch);

        $sections = $this->allSections($dispatch);

        return response()->streamDownload(function () use ($sections) {
            $zip = new ZipStream(sendHttpHeaders: false);

            foreach ($sections as $entry) {
                [$view, $data] = $this->singleViewData($entry['challan']);
                $pdf = Pdf::loadView($view, $data)->output();

                $zip->addFile(fileName: "{$entry['challan']->challan_no}.pdf", data: $pdf);
            }

            $zip->finish();
        }, "{$dispatch->dispatch_no}-challans.zip", ['Content-Type' => 'application/zip']);
    }

    private function renderSingle(Challan $challan, bool $isPublic = false)
    {
        [$view, $data] = $this->singleViewData($challan);

        return view($view, $data + ['isPublic' => $isPublic]);
    }

    private function singleViewData(Challan $challan): array
    {
        $challan->loadMissing(['dispatch.vehicle', 'dispatch.vehicleAssignment.marketingOfficer', 'dispatch.vehicleAssignment.dispatchPlan', 'dealer.village', 'dealer.taluka', 'dealer.district', 'farmer.village', 'farmer.taluka', 'farmer.district', 'createdBy', 'parentChallan']);

        $lines = $challan->lines()->with(['dealer', 'farmer', 'booking'])->get();

        $view = $challan->type === Challan::TYPE_DEALER ? 'challans.dealer' : 'challans.farmer';

        return [$view, ['challan' => $challan, 'dispatch' => $challan->dispatch, 'lines' => $lines]];
    }

    /**
     * Every Farmer challan across every dealer on this dispatch, each
     * carrying its own scoped lines.
     */
    private function farmerEntries(Dispatch $dispatch): Collection
    {
        return Challan::where('dispatch_id', $dispatch->id)
            ->where('type', Challan::TYPE_FARMER)
            ->with(['dealer', 'farmer.village', 'farmer.taluka', 'farmer.district', 'createdBy', 'parentChallan'])
            ->orderBy('challan_no')
            ->get()
            ->map(fn (Challan $challan) => [
                'challan' => $challan,
                'lines' => $challan->lines()->with(['dealer', 'farmer', 'booking'])->get(),
            ]);
    }

    /**
     * Dealer challan followed immediately by its own Farmer challans, for
     * every dealer on this dispatch — the order "Print All" and the ZIP
     * both render in.
     */
    private function allSections(Dispatch $dispatch): Collection
    {
        $dealerChallans = Challan::where('dispatch_id', $dispatch->id)
            ->where('type', Challan::TYPE_DEALER)
            ->with(['dealer.village', 'dealer.taluka', 'dealer.district', 'createdBy'])
            ->orderBy('challan_no')
            ->get();

        return $dealerChallans->flatMap(function (Challan $dealerChallan) {
            $sections = collect([[
                'type' => Challan::TYPE_DEALER,
                'challan' => $dealerChallan,
                'lines' => $dealerChallan->lines()->with(['dealer', 'farmer', 'booking'])->get(),
            ]]);

            $farmerChallans = $dealerChallan->childChallans()
                ->with(['dealer', 'farmer.village', 'farmer.taluka', 'farmer.district', 'createdBy', 'parentChallan'])
                ->orderBy('challan_no')
                ->get();

            return $sections->concat($farmerChallans->map(fn (Challan $farmerChallan) => [
                'type' => Challan::TYPE_FARMER,
                'challan' => $farmerChallan,
                'lines' => $farmerChallan->lines()->with(['dealer', 'farmer', 'booking'])->get(),
            ]));
        });
    }
}
